application:
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "yale@omg.lol"
  authorization_token: "my-secret-token"
  timeout_millis: 10000
